language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t logan-exe/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true logan-exe/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-100316009250"
  bucket_path: "docker-react"
  on:
    branch: master
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_KEY
